name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Run tests with coverage
      run: |
        poetry run coverage run --source=simple_cov_badge -m pytest tests/
        poetry run coverage report
    - name: Generate XML coverage report
      run: |
        poetry run coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


    # - name: Run tests with coverage
    #   run: poetry run pytest --cov=simple_cov_badge tests/
    # - name: Upload coverage to Codecov
    #   run: poetry run codecov
    # - name: Upload coverage reports to Codecov
    #   uses: codecov/codecov-action@v3
    #   env:
    #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
